### ISSUE TITLE
2:2 계획이 있으신지?!

### ISSUE THREAD

**Issue by ghk829** [gorisanson/pikachu-volleyball-p2p-online#14]

**Comment by ghk829** [comment]
2:2 계획이 있나요?
시간되시면 2:2 만들어주시면 너무 감사하겠습니다 ㅜㅜ

**Comment by gorisanson** [comment]
@ghk829 재밌게 플레이해주셔서 감사합니다! 피카츄 배구 온라인 2:2 버전을 만들 계획이 저에게는 현재 없습니다. 죄송합니다..ㅠㅠ 여기에 공개된 소스코드를 바탕으로 2:2 대전을 직접 혹은 다른 분과 함께 만들어볼 수 있을 것 같습니다.
