### ISSUE TITLE
[BUG] 네트망을 뚫는 스파이크

### ISSUE THREAD

**Issue by skeksk91** [gorisanson/pikachu-volleyball-p2p-online#18]
네트망을 뚫는 스파이크는 기존 게임에도 있던 버그인데,
어떻게 고칠 방법이 있을까요?

**Comment by gorisanson** [comment]
@skeksk91 
네트를 뚫는 스파이크를 막는 방법은 물론 있습니다. 네트가 공의 운동에 미치는 영향을 다루는 코드를 변경하면 됩니다. 물리 엔진과 관련된 것이니 [src/resources/js/offline_version_js/physics.js](physics.js) 파일에 담겨 있습니다.

---

### 네트를 뚫는 스파이크가 발생하는 원인

네트를 뚫는 스파이크가 어떻게 게임에서 발생하는지 그 원인에 관해 코드를 살펴보면서 설명하겠습니다.

https://github.com/gorisanson/pikachu-volleyball-p2p-online/blob/b0cb74cd7a387ceb72498588da90d8419b5088e1/src/resources/js/offline_version_js/physics.js#L446-L462

위의 **446-462번 줄에 걸쳐 있는 코드**가 네트가 공의 움직임에 미치는 작용을 다룹니다. 

**447-450번 줄에 걸쳐 있는 if 문**에서는 우선 공의 x좌표(`ball.x`)와 공의 y좌표(`ball.y`)를 검사해 저 조건에 맞으면 공이 네트에 닿은 것으로 간주해 if 문 내부의 코드를 실행합니다. (참고로, 공의 x좌표는 오른쪽 방향이 양의 방향이고, 공의 y좌표는 아래 방향이 양의 방향입니다.) 

그 후, 451번 줄에 있는 if 조건을 검사해서. 조건에 맞으면 452-454번 줄을 실행해 공을 위 방향으로 튕겨내고, 조건에 맞지 않으면 456-460번 줄을 실행해 공을 좌우 방향으로 네트 반대방향으로 튕겨냅니다.

위 if 문 안에 있는 상수들의 값을 보시면 다음과 같습니다.

https://github.com/gorisanson/pikachu-volleyball-p2p-online/blob/b0cb74cd7a387ceb72498588da90d8419b5088e1/src/resources/js/offline_version_js/physics.js#L32-L35

https://github.com/gorisanson/pikachu-volleyball-p2p-online/blob/b0cb74cd7a387ceb72498588da90d8419b5088e1/src/resources/js/offline_version_js/physics.js#L46-L51

아래 네트를 뚫는 스파이크 캡처 이미지에서의 공의 좌표를 적으면 다음과 같습니다.

<img width="706" alt="Screen Shot 2020-07-30 at 9 27 28 PM" src="https://user-images.githubusercontent.com/38519601/88922743-802e9b00-d2ab-11ea-94f7-89586035a7cb.png">

```
파란 그림자 중심 좌표:    (x: 178, y: 140)
하이퍼볼 그림자 중심 좌표: (x: 198, y: 172)
공 중심 좌표:           (x: 218, y: 205)
```

`하이퍼볼 그림자 중심 좌표` -> `공 중심 좌표`로 공이 이동하는 순간에 네트를 뚫는 것을 확인할 수 있습니다. 좌표를 살펴보면 현재 공의 좌표가 `하이퍼볼 그림자 중심 좌표: (x: 198, y: 172)`일 때는 위에서 언급한 **447-450번 줄에 걸쳐 있는 if 문** 조건에 걸리지 않아 (`ball.y == 172`이고 `NET_PILLAR_TOP_TOP_Y_COORD == 176`이기 때문에 `ball.y > NET_PILLAR_TOP_TOP_Y_COORD` 조건에 해당하지 않습니다) 네트에 닿았다는 판정을 받지 않게 됩니다. 따라서 공은 그냥 네트가 없는 것처럼 진행하게 되고 `공 중심 좌표: (x: 218, y: 205)`로 진행하여 x좌표가 `GROUND_HALF_WIDTH == 216`에 위치한 네트를 그냥 통과하게 되는 것입니다.

---

### 네트를 뚫는 스파이크를 막는 방법

방법은 여러가지가 있을 수 있습니다. 기존 게임성을 최대한 유지하면서 막는 한 가지 방법으로 떠오르는 것은 다음과 같습니다. 현재 공의 위치와 예상되는 다음 공의 위치를 사이에 선분을 그어, 그 선분이 x좌표가 `GROUND_HALF_WIDTH == 216`이고 y좌표가 `NET_PILLAR_TOP_TOP_Y_COORD == 176`보다 큰 지점에 걸쳐있는 네트를 지나는지 체크하고, 만약 그 선분이 네트를 지나게 된다면 네트에 닿은 효과를 공에 미쳐서 다음 공의 위치를 그에 따라 변경하는 방법입니다. 다음 코드를 위에서 언급한 **442-462번 줄에 걸쳐 있는 코드** 바로 이전에 삽입하면 됩니다.

```javascript
  if (
    (ball.x < GROUND_HALF_WIDTH && futureBallX > GROUND_HALF_WIDTH) ||
    (ball.x > GROUND_HALF_WIDTH && futureBallX < GROUND_HALF_WIDTH)
  ) {
    // ballYOnNet:
    // calculated y coordinate of the ball
    // when it go over x coordinate (GROUND_HALF_WIDTH) of the net
    const ballYOnNet =
      ((futureBallY - ball.y) / (futureBallX - ball.x)) *
        (GROUND_HALF_WIDTH - ball.x) +
      ball.y;
    if (ballYOnNet > NET_PILLAR_TOP_TOP_Y_COORD) {
      if (ballYOnNet <= NET_PILLAR_TOP_BOTTOM_Y_COORD) {
        if (ball.yVelocity > 0) {
          ball.yVelocity = -ball.yVelocity;
        }
      } else {
        if (ball.x < GROUND_HALF_WIDTH) {
          ball.xVelocity = -Math.abs(ball.xVelocity);
        } else {
          ball.xVelocity = Math.abs(ball.xVelocity);
        }
      }
    }
  }
```
위 코드를 삽입한 후 실행해보면, 이전에 네트를 뚫었던 동일한 스파이크를 키보드로 조작해보았을 때 다음과 같은 결과가 얻어집니다.

<img width="708" alt="Screen Shot 2020-07-30 at 9 29 14 PM" src="https://user-images.githubusercontent.com/38519601/88922885-c2f07300-d2ab-11ea-9082-98746609e492.png">

```
파란 그림자 중심 좌표:    (x: 178, y: 140)
하이퍼볼 그림자 중심 좌표: (x: 198, y: 172)
공 중심 좌표:           (x: 178, y: 205)
```

동일한 스파이크를 키보드로 조작했기에 `파란 그림자 중심 좌표`와 `하이퍼볼 그림자 중심 좌표`가 이전 이미지와 동일하나 공이 네트를 뚫지 못한 것을 확인할 수 있습니다.

---

### 네트를 뚫는 스파이크를 막을 것인가?

저는 제가 관리하고 있는 다음 두 사이트

[피카츄 배구 (오프라인 웹 버전)](https://gorisanson.github.io/pikachu-volleyball/ko/)
[피카츄 배구 P2P 온라인](https://gorisanson.github.io/pikachu-volleyball-p2p-online/ko/)

에서 네트를 뚫는 스파이크를 막지 않을 생각입니다.

피카츄 배구에는 네트를 뚫는 스파이크 외에도, 공의 좌표가 `GROUND_HALF_WIDTH == 216`일 때 세게 치기를 하면 왼쪽 피카츄가 세게 치기를 하더라도 공이 왼쪽 방향으로 나가는 버그가 있습니다. 이 버그도 어렵지 않게 수정이 가능하나 버그를 수정하지 않고 유지하고 있습니다. 원조 게임을 제가 만든 것이 아니고, 또 많은 분들이 이런 버그가 존재함에도 원조 피카츄 배구를 좋아하고, 또 이런 버그를 이용한 기술들을 이용하는 분들도 있기 때문입니다. 벽을 뚫는 스파이크 또한 일종의 기술이고 게임의 재미를 더해주는 요소라고 생각합니다. 따라서 네트를 뚫는 스파이크를 막지 않을 생각입니다.

네트를 뚫는 스파이크를 막는 버전을 플레이하고 싶으신 경우, [피카츄 배구 오프라인 버전 기트허브 저장소](https://github.com/gorisanson/pikachu-volleyball)에 있는 소스 코드에 제가 위에 말씀드린 수정 코드를 삽입하여 실행한 후 플레이 하실 수 있습니다.

**Comment by skeksk91** [comment]
진정한 피카츄배구 수호자는 버그까지 포용할 줄 알아야 ~! ㅎㅎ 

답변 덕분에 궁금증이 해소됐습니다 감사합니다.
