### ISSUE TITLE
Add filters to background

### ISSUE THREAD

**Issue by KNHui** [gorisanson/pikachu-volleyball-p2p-online#5]
Characters in the background distract attention when pop-up content appears.
In this case, I think it is necessary to add filters like "blur" and "grayscale" to the background to make the popup content look better.

**Comment by gorisanson** [comment]
@KNHui Thank you for your suggestion! But I don't get what you mean by "pop-up content". Can you specify a little bit more? If you can attach an image, it would be great!

**Comment by gorisanson** [comment]
@KNHui Oh, now I got it! You mean the pop-up content which appears if we change options like "speed" or "winning score", and which also appears when the peer-to-peer connection is disconnected. Thank you for your suggestion!

**Comment by gorisanson** [comment]
@KNHui I added blurring backdrop-filter on commit 01077db6058302c2918726f2e021881620baa1cd, and merged it to master branch and deployed it. Can you check whether it is OK?

**Comment by KNHui** [comment]
Well done. That's what I suggested.
However, you didn't add a 'grayscale' filter.
How about putting a 'grayscale' filter, too?
```
backdrop-filter: blur(10px) grayscale(90%);
-webkit-backdrop-filter: blur(10px) grayscale(90%);
```

- non grayscale
![1](https://user-images.githubusercontent.com/37471802/82728069-1765f800-9d29-11ea-9be3-0f855632a530.png)
- grayscale
![22](https://user-images.githubusercontent.com/37471802/82728075-1a60e880-9d29-11ea-829f-bfda331aebde.jpg)

- non grayscale
![3](https://user-images.githubusercontent.com/37471802/82728078-1b921580-9d29-11ea-89b5-660da15cd74b.png)
- grayscale
![333](https://user-images.githubusercontent.com/37471802/82728080-1cc34280-9d29-11ea-8d3b-43b725f1a3cf.jpg)

**Comment by gorisanson** [comment]
@KNHui Thanks for your kind suggestion! I tested it on my machine. But, to me, it looks better when just only applying blur, not grayscale. It looks somewhat pale to me when applying grayscale..
